// actions types used in home page are defined here
export const LECTURER_EDIT_PROFILE = 'LECTURER_EDIT_PROFILE';
export const LECTURER_EDIT_PROFILE_SUCCESS = 'LECTURER_EDIT_PROFILE_SUCCESS';
export const LECTURER_EDIT_PROFILE_ERROR = 'LECTURER_EDIT_PROFILE_ERROR';
